baldm0mma/verify_aptyum/ update to use RPM repo

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -3201,11 +3201,25 @@ steps:
   - 'echo "Step 2: Installing prerequisites..."'
   - dnf install -y dnf-utils >/dev/null 2>&1
   - 'echo "Step 3: Adding Grafana GPG key..."'
-  - rpm --import https://packages.grafana.com/gpg.key
-  - 'echo "Step 4: Installing Grafana..."'
+  - rpm --import https://rpm.grafana.com/gpg.key
+  - 'echo "Step 4: Configuring Grafana repository..."'
+  - |-
+    echo '[grafana]
+    name=grafana
+    baseurl=https://rpm.grafana.com
+    repo_gpgcheck=1
+    enabled=1
+    gpgcheck=1
+    gpgkey=https://rpm.grafana.com/gpg.key
+    sslverify=1
+    sslcacert=/etc/pki/tls/certs/ca-bundle.crt
+    ' > /etc/yum.repos.d/grafana.repo
+  - 'echo "Step 5: Checking RPM repository..."'
+  - dnf list available grafana-${TAG} >/dev/null 2>&1
+  - if [ $? -eq 0 ]; then
+  - '    echo "Grafana package found in repository. Installing from repo..."'
   - for i in $(seq 1 10); do
-  - '    if dnf install -y https://dl.grafana.com/oss/release/grafana-${TAG}-1.x86_64.rpm
-    >/dev/null 2>&1; then'
+  - '    if dnf install -y grafana-${TAG} >/dev/null 2>&1; then'
   - '        echo "Command succeeded on attempt $i"'
   - '        break'
   - '    else'
@@ -3218,7 +3232,11 @@ steps:
   - '        sleep 60'
   - '    fi'
   - done
-  - 'echo "Step 5: Verifying Grafana installation..."'
+  - else
+  - '    echo "Grafana package version ${TAG} not found in repository."'
+  - '    exit 1'
+  - fi
+  - 'echo "Step 6: Verifying Grafana installation..."'
   - if rpm -q grafana | grep -q "${TAG}"; then
   - '    echo "Successfully verified Grafana version ${TAG}"'
   - else
@@ -3356,11 +3374,25 @@ steps:
   - 'echo "Step 2: Installing prerequisites..."'
   - dnf install -y dnf-utils >/dev/null 2>&1
   - 'echo "Step 3: Adding Grafana GPG key..."'
-  - rpm --import https://packages.grafana.com/gpg.key
-  - 'echo "Step 4: Installing Grafana..."'
+  - rpm --import https://rpm.grafana.com/gpg.key
+  - 'echo "Step 4: Configuring Grafana repository..."'
+  - |-
+    echo '[grafana]
+    name=grafana
+    baseurl=https://rpm.grafana.com
+    repo_gpgcheck=1
+    enabled=1
+    gpgcheck=1
+    gpgkey=https://rpm.grafana.com/gpg.key
+    sslverify=1
+    sslcacert=/etc/pki/tls/certs/ca-bundle.crt
+    ' > /etc/yum.repos.d/grafana.repo
+  - 'echo "Step 5: Checking RPM repository..."'
+  - dnf list available grafana-${TAG} >/dev/null 2>&1
+  - if [ $? -eq 0 ]; then
+  - '    echo "Grafana package found in repository. Installing from repo..."'
   - for i in $(seq 1 10); do
-  - '    if dnf install -y https://dl.grafana.com/oss/release/grafana-${TAG}-1.x86_64.rpm
-    >/dev/null 2>&1; then'
+  - '    if dnf install -y grafana-${TAG} >/dev/null 2>&1; then'
   - '        echo "Command succeeded on attempt $i"'
   - '        break'
   - '    else'
@@ -3373,7 +3405,11 @@ steps:
   - '        sleep 60'
   - '    fi'
   - done
-  - 'echo "Step 5: Verifying Grafana installation..."'
+  - else
+  - '    echo "Grafana package version ${TAG} not found in repository."'
+  - '    exit 1'
+  - fi
+  - 'echo "Step 6: Verifying Grafana installation..."'
   - if rpm -q grafana | grep -q "${TAG}"; then
   - '    echo "Successfully verified Grafana version ${TAG}"'
   - else
@@ -5362,6 +5398,6 @@ kind: secret
 name: gcr_credentials
 ---
 kind: signature
-hmac: 71d66c29948194fd057339ff0151669f6b051fc135fed3640a856ce21da53902
+hmac: a573fe30078cd7d6f761c00279266094c1b39dd9ff20b2bde8523030996bb1af
 
 ...
