Make e2e test depend on binary builds

diff --git a/scripts/grafana-server/start-server b/scripts/grafana-server/start-server
--- a/scripts/grafana-server/start-server
+++ b/scripts/grafana-server/start-server
@@ -12,33 +12,24 @@ mkdir $RUNDIR
 
 echo -e "Copying grafana backend files to temp dir..."
 
-# Expand any wildcards
-pkgs=(${PACKAGE_FILE})
-pkg=${pkgs[0]}
-if [[ -f ${pkg} ]]; then
-  echo "Found package tar file ${pkg}, extracting..."
-  tar zxf ${pkg} -C $RUNDIR
-  mv $RUNDIR/grafana-*/* $RUNDIR
-else
-  echo "Couldn't find package ${PACKAGE_FILE} - copying local dev files"
+echo "Couldn't find package ${PACKAGE_FILE} - copying local dev files"
 
-  if [[ ! -f bin/grafana-server ]]; then
-    echo bin/grafana-server missing
-    exit 1
-  fi
-
-  cp -r ./bin $RUNDIR
-  cp -r ./public $RUNDIR
-  cp -r ./tools $RUNDIR
-
-  mkdir $RUNDIR/conf
-  mkdir $PROV_DIR
-  mkdir $PROV_DIR/datasources
-  mkdir $PROV_DIR/dashboards
-
-  cp ./scripts/grafana-server/custom.ini $RUNDIR/conf/custom.ini
-  cp ./conf/defaults.ini $RUNDIR/conf/defaults.ini
+if [[ ! -f bin/grafana-server ]]; then
+  echo bin/grafana-server missing
+  exit 1
 fi
+
+cp -r ./bin $RUNDIR
+cp -r ./public $RUNDIR
+cp -r ./tools $RUNDIR
+
+mkdir $RUNDIR/conf
+mkdir $PROV_DIR
+mkdir $PROV_DIR/datasources
+mkdir $PROV_DIR/dashboards
+
+cp ./scripts/grafana-server/custom.ini $RUNDIR/conf/custom.ini
+cp ./conf/defaults.ini $RUNDIR/conf/defaults.ini
 
 echo -e "Copy provisioning setup from devenv"
 
