[release-12.3.8] CI: backport Makefile and release-build changes (#122140)
* [release-12.4.3] CI: Use make for building and fix ci checks not functioning in mirror (#122006)

* [release-12.4.3] Backport Makefile and GHA fixes

* add missing setup-go action

* add missing report-go-cache-sizes action

* Update Dockerfile

* fix make gen-cue

* add missing setup-actions

* update dockerignore

* git checkout main -- .github/actions/yarn-install

* fix lint errors

* remove cleanup update from makefile

* restore make gen-go logic

* Revert change to make fix-cue

* fix cue again?

* skip test that will never pass...

* fix superfluous import

(cherry picked from commit 19d10ac7999d13ef529bc3fb7dc59d10b71ac841)

* make build-go needs to build grafana-cli and grafana-server (#122125)

(cherry picked from commit fd8b0f24457e049451f1cb79c227b386dbc65342)

* Fix actionlint errors

diff --git a/.github/actions/setup-enterprise/action.yml b/.github/actions/setup-enterprise/action.yml
--- a/.github/actions/setup-enterprise/action.yml
+++ b/.github/actions/setup-enterprise/action.yml
@@ -33,7 +33,24 @@ runs:
       env:
         GH_TOKEN: ${{ steps.generate_token.outputs.token }}
       run: |
-        git clone https://x-access-token:${GH_TOKEN}@github.com/grafana/grafana-enterprise.git ../grafana-enterprise;
+        RETRIES="5"
+        grafana_root="$PWD"
+
+        for i in $(seq 1 $RETRIES); do
+          echo "Attempt $i to clone..."
+
+          if git clone https://x-access-token:${GH_TOKEN}@github.com/grafana/grafana-enterprise.git ../grafana-enterprise; then
+            echo "Clone succeeded on attempt $i"
+            break
+          fi
+
+          if [ $i -eq $RETRIES ]; then
+            echo "Clone failed after $RETRIES attempts, failing pipeline."
+            exit 1
+          fi
+
+          sleep "$i"
+        done
 
         cd ../grafana-enterprise
 
@@ -45,4 +62,4 @@ runs:
           git checkout main
         fi
 
-        QUIET=1 ./build.sh
+        QUIET=1 ./build.sh "$grafana_root"
