Chore: Replace Husky/Lint-staged with Lefthook (#66608)
* Switch from husky+precommit to lefthook

Migrate from husky/precommit to lefthook

h

old husky precommit

lefthook so far

remove husky folder

switch to new lefthook package

Add postinstall script to clean up after husky

preinstall to remove husky config

package.json

package.json

package.json

script

v

Reduce lefthook output

Cleanup

testing

reduce output

testing betterer

testing betterer

testing betterer

testing betterer

testing betterer

testing betterer

testing betterer

skip skipping execution info

small cleanup

remove comment from testing

clean up old husky hooks in .git/hooks path

run scripts in parallel

update codeowners

don't auto-install lefthook

install lefthook with make command

fix yarn checksum

* update codeowners

* don't use source because it isn't available in ubuntu/debian's /bin/sh

* Ensure lefthook commits files fixed by precommit hooks

* add comment to lefthook.rc explaining what it does

* add i18n:pseudo precommit

* Don't create .husky/safe-to-delete file anymore

* cleanup old lint-staged config

* contribute docs

* update lefthook to 1.4.8

* Move frontend encouragement docs

* rewrite husky cleanup script in bash so we can run it with make

* Make old husky precommit script reject commits until husky is removed

* log precommit warning for everyone

* fix package.json

* run lefthook hooks from old husky hook

* run lefthook hooks from old husky hook

* comments

* codeowners

* codeowners

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,30 @@
 #!/bin/sh
 
-# Ignore husky hooks if no frontend code has been changed
-git diff --cached --name-only | grep -v --quiet "^pkg/" || exit 0
+# Catch devs who have installed lefthook, went back into the past and reinstalled husky,
+# then came back into lefthook-land.
+if [ -f ".git/hooks/pre-commit" ]; then
+  if grep -q lefthook ".git/hooks/pre-commit"; then
+    # Remove husky from their git config
+    env SILENT=1 ./scripts/cleanup-husky.sh
 
-. "$(dirname "$0")/_/husky.sh"
+    # And run the lefthook precommit hook instead of this
+    ./.git/hooks/pre-commit "$@"
+    exit $?
+  fi
+fi
 
-yarn run precommit
+# This precommit hook exists only for people who still have hooksPath=.husky in their git config
+# from when we used husky. This is intended to run only on first commit after pulling the lefthook changes.
+#
+# Either setting up lefthook, or running the clean command will unset the hooksPath git config so this
+# hook is no longer ran when committing.
+
+echo "\n⚠️⚠️⚠️ \e[1mImportant: Pre-commit hooks are now opt-in.\e[0m ⚠️⚠️⚠️"
+echo "To install the new pre-commit hooks:"
+echo "  $ \e[96mmake lefthook-install\e[0m"
+echo "Or, silence this message by cleaning up the old hooks"
+echo "  $ \e[96mmake cleanup-old-git-hooks\e[0m"
+echo "\nPre-commit hooks will not run on this commit and it will be committed even if it contains lint errors."
+echo "See https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#configure-precommit-hooks for more info\n"
+
+exit 0
