Fix client generation command

diff --git a/.github/workflows/frontend-lint.yml b/.github/workflows/frontend-lint.yml
--- a/.github/workflows/frontend-lint.yml
+++ b/.github/workflows/frontend-lint.yml
@@ -177,7 +177,7 @@ jobs:
     - name: Generate API clients
       run: |
         extract_error_message='ERROR! API client generation failed!'
-        yarn generate-apis || (echo "${extract_error_message}" && false)
+        yarn workspace @grafana/api-clients generate-apis || (echo "${extract_error_message}" && false)
     - name: Verify generated clients
       run: |
         uncommited_error_message="ERROR! API client generation has not been committed. Please run 'yarn generate-apis', commit the changes and push again."
