tidy up

diff --git a/.github/workflows/pr-e2e-tests.yml b/.github/workflows/pr-e2e-tests.yml
--- a/.github/workflows/pr-e2e-tests.yml
+++ b/.github/workflows/pr-e2e-tests.yml
@@ -29,7 +29,6 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          path: ./grafana
           persist-credentials: false
 
       # TODO: add a cleanup workflow to remove the cache when the PR is closed
@@ -38,7 +37,7 @@ jobs:
       - uses: actions/cache@v4
         id: cache
         with:
-          key: "xx_build-grafana-${{ runner.os }}-${{ hashFiles('yarn.lock', '/public/*',  '/packages/*', '/pkg/**/*.go', '**/go.mod', '**/go.sum') }}"
+          key: "build-grafana-${{ runner.os }}-${{ hashFiles('yarn.lock', 'public/*',  'packages/*', 'pkg/**/*.go', '**/go.mod', '**/go.sum', '!**_test.go', '!**.test.ts', '!**.test.tsx') }}"
           path: |
             build-dir
 
@@ -54,7 +53,7 @@ jobs:
         with:
           verb: run
           cloud-token: ${{ secrets.TEMP_DAGGER_TOKEN_JOSH }} # TODO: remove before merging
-          args: go -C grafana run ./pkg/build/cmd artifacts -a targz:grafana:linux/amd64 --grafana-dir="${PWD}/grafana" > out.txt
+          args: go run ./pkg/build/cmd artifacts -a targz:grafana:linux/amd64 --grafana-dir="${PWD}/grafana" > out.txt
       - name: Cat built artifact
         if: steps.cache.outputs.cache-hit != 'true'
         run: cat out.txt
@@ -78,7 +77,7 @@ jobs:
           ls -lah build-dir
 
       - name: Set artifact name
-        run: echo "artifact=grafana-e2e-${{github.run_number}}" >> "$GITHUB_OUTPUT"
+        run: echo "artifact=grafana-server-${{github.run_number}}" >> "$GITHUB_OUTPUT"
         id: artifact
 
       - name: Upload artifact
@@ -89,6 +88,7 @@ jobs:
           name: ${{ steps.artifact.outputs.artifact }}
           path: build-dir/grafana.tar.gz
 
+  # TODO: we won't need this when we only have playwright
   build-e2e-runner:
     name: Build E2E test runner
     runs-on: ubuntu-latest
@@ -223,6 +223,7 @@ jobs:
   required-playwright-tests:
     needs:
       - run-playwright-tests
+      - build-grafana
     if: ${{ !cancelled() }}
     name: All Playwright tests complete
     runs-on: ubuntu-latest
@@ -247,12 +248,22 @@ jobs:
       - name: Download blob reports from GitHub Actions Artifacts
         uses: actions/download-artifact@v4
         with:
-          path: all-blob-reports
+          path: blobs
           pattern: playwright-blob-*
           merge-multiple: true
 
+      - name: Check blob reports
+        run: |
+          if [ ! "$(ls -A ./blobs)" ]; then
+            echo "Error: No blob reports found in ./blobs directory"
+            echo "Did the Playwright tests run at all?"
+            exit 1
+          fi
+          echo "Found blob reports in ./blobs:"
+          ls -lah ./blobs
+
       - name: Merge into HTML Report
-        run: npx playwright merge-reports --reporter html ./all-blob-reports
+        run: npx playwright merge-reports --reporter html ./blobs
 
       - name: Upload HTML report
         uses: actions/upload-artifact@v4
@@ -305,6 +316,7 @@ jobs:
   required-e2e-tests:
     needs:
       - run-e2e-tests
+      - build-grafana
       # a11y test is not listed on purpose: it is not an important E2E test.
       # It is also totally fine to fail right now.
     # always() is the best function here.
