try to cache the grafana build

diff --git a/.github/workflows/pr-e2e-tests.yml b/.github/workflows/pr-e2e-tests.yml
--- a/.github/workflows/pr-e2e-tests.yml
+++ b/.github/workflows/pr-e2e-tests.yml
@@ -14,6 +14,7 @@ on:
 
 permissions: {}
 
+
 jobs:
   build-grafana:
     name: Build & Package Grafana
@@ -27,15 +28,53 @@ jobs:
         with:
           path: ./grafana
           persist-credentials: false
-      - uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e
+      - uses: actions/cache@v4
+        id: cache
+        with:
+          # Ensure this cache key is identical to the one in run-playwright-tests
+          key: "build-grafana-${{ runner.os }}-${{ hashFiles('yarn.lock', '/public/*',  '/packages/*', '/pkg/**/*.go', '**/go.mod', '**/go.sum') }}"
+          path: |
+            dist
+
+      # If no cache hit, build Grafana
+      - name: Build Grafana
+        if: steps.cache.outputs.cache-hit != 'true'
+        uses: dagger/dagger-for-github@e47aba410ef9bb9ed81a4d2a97df31061e5e842e
         with:
           verb: run
           cloud-token: ${{ secrets.TEMP_DAGGER_TOKEN_JOSH }} # TODO: remove before merging
           args: go -C grafana run ./pkg/build/cmd artifacts -a targz:grafana:linux/amd64 --grafana-dir="${PWD}/grafana" > out.txt
-      - run: mv "$(cat out.txt)" grafana.tar.gz
-      - run: echo "artifact=grafana-e2e-${{github.run_number}}" >> "$GITHUB_OUTPUT"
+      - name: Move built artifact
+        if: steps.cache.outputs.cache-hit != 'true'
+        run: mv "$(cat out.txt)" grafana.tar.gz
+
+      # If cache hit, move the artifact to the correct location
+      - name: Move artifact
+        if: steps.cache.outputs.cache-hit == 'true'
+        run: |
+          # Check number of files in dist directory
+          file_count=$(ls -1 ./dist | wc -l)
+          if [ "$file_count" -ne 1 ]; then
+            echo "Error: Expected exactly one file in dist directory, found $file_count"
+            exit 1
+          fi
+
+          # Check if the file is a .tar.gz
+          file=$(ls ./dist)
+          if [[ $file != *.tar.gz ]]; then
+            echo "Error: File in dist directory is not a .tar.gz file"
+            exit 1
+          fi
+
+          # Move the file
+          mv "./dist/$file" ./grafana.tar.gz
+
+      - name: Set artifact name
+        run: echo "artifact=grafana-e2e-${{github.run_number}}" >> "$GITHUB_OUTPUT"
         id: artifact
-      - uses: actions/upload-artifact@v4
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
         id: upload
         with:
           retention-days: 1
