add legacy search case

diff --git a/.github/workflows/run-dashboard-search-e2e.yml b/.github/workflows/run-dashboard-search-e2e.yml
--- a/.github/workflows/run-dashboard-search-e2e.yml
+++ b/.github/workflows/run-dashboard-search-e2e.yml
@@ -60,6 +60,10 @@ jobs:
         run: |
           cp -rf ${{ github.workspace }}/e2e/dashboards-search-suite/mode5.ini ${{ github.workspace }}/scripts/grafana-server/custom.ini
           yarn e2e:dashboards-search || echo "Test failed but marking as success since unified search is behind a feature flag and should not block PRs"
+      - name: Run dashboard search e2e mode2 legacy search
+        run: |
+          cp -rf ${{ github.workspace }}/e2e/dashboards-search-suite/mode2-legacy-search.ini ${{ github.workspace }}/scripts/grafana-server/custom.ini
+          yarn e2e:dashboards-search || echo "Test failed but marking as success since unified search is behind a feature flag and should not block PRs"
       - name: Always succeed # This is a workaround to make the job pass even if the previous step fails
         if: failure()
         run: exit 0
